modLoader = "javafml"
loaderVersion = "[38,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "forge_test_mod"
version = "${version}"
displayName = "Matrix Forge"
authors = "gamma_02, the DimDoors team"
description = '''
Simple annotation-based registry for Forge
'''
#logoFile = ""

[[dependencies.forge_test_mod]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forge_test_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forge_test_mod]]
modId = "architectury"
mandatory = true
versionRange = "[3.6.15,)"
ordering = "AFTER"
side = "BOTH"